### ISSUE TITLE
Remove espionage

### ISSUE THREAD

**Issue by KOLANICH** [NHellFire/KernelAdiutor#4]
A sharing feature.

**Comment by ghost** [comment]
@KOLANICH I'm sorry, what?
Could you clarify this. Do you mean the app track the user ("espionage"), or you want a sharing feature??

**Comment by KOLANICH** [comment]
https://github.com/NHellfire/KernelAdiutor/blob/master/app/src/main/java/com/grarak/kerneladiutor/services/monitor/Monitor.java#L82
https://github.com/NHellfire/KernelAdiutor/blob/master/app/src/main/java/com/grarak/kerneladiutor/services/monitor/Monitor.java#L108-L154
https://github.com/NHellfire/KernelAdiutor/blob/master/app/src/main/java/com/grarak/kerneladiutor/utils/server/ServerCreateDevice.java#L42

Please note, that by default sharing is on.

**Comment by ghost** [comment]
jfc... you're right!
I didn't had time time take a look at the code back then, I didn't even noticed the sharing F feature! And you are right, it's enabled by default. The firewall probably blocked everything, but this is bad!

I blindly trusted this because I saw no anti-features warning on F-Droid.
I think if this don't get removed, it should get flagged with anti-features "Tracking", I will report it myself.

btw, thanks for the clarification.

**Comment by NHellFire** [comment]
The info on f-droid is nothing to do with me. Someone else submitted this fork to them. Data sharing has now been entirely removed.

**Comment by ghost** [comment]
Many Thanks.

**Comment by KOLANICH** [comment]
@NHellfire, thank you.
