### ISSUE TITLE
Add a "0.9.73.3-fdroid0" tag

### ISSUE THREAD

**Issue by flocke** [NHellFire/KernelAdiutor#5]
Could you add a tag "0.9.73.3-fdroid0" to the git repo?
If the tag does not exist the F-Droid build will fail (it needs a tag with exactly the same name as the version in build.gradle. See https://gitlab.com/fdroid/rfp/issues/333

**Comment by NHellFire** [comment]
Done (wasn't aware fdroid needs tag to match exactly)

On 13 Jan 2018 12:27, "Jakob Nixdorf" <notifications@github.com> wrote:

Could you add a tag "0.9.73.3-fdroid0" to the git repo?
If the tag does not exist the F-Droid build will fail (it needs a tag with
exactly the same name as the version in build.gradle. See
https://gitlab.com/fdroid/rfp/issues/333

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NHellFire/KernelAdiutor/issues/5>, or mute the thread

**Comment by flocke** [comment]
Yeah, I figured that out when OpenLauncher didn't build and I tried to fix it. I think it tries to check out the tag matching the version name in the build.gradle during build.

**Comment by flocke** [comment]
I will close the issue once the F-Droid build is out.

**Comment by flocke** [comment]
The new version just hit F-Droid, thanks for adding the tag.
